// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-ZzQCa5e5eKCTQJ2dYfs-7HZ0KTE1jY8',
    appId: '1:845399101862:web:42db3cfcece2ff200fff67',
    messagingSenderId: '845399101862',
    projectId: 'hydrate-349220',
    authDomain: 'hydrate-349220.firebaseapp.com',
    storageBucket: 'hydrate-349220.appspot.com',
    measurementId: 'G-SXFJXYFJMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrJLzkFcotzSu_GCPjjbEeX52X7_mRe2g',
    appId: '1:845399101862:android:f96e877ce5bb2a9c0fff67',
    messagingSenderId: '845399101862',
    projectId: 'hydrate-349220',
    storageBucket: 'hydrate-349220.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Dm67YQrLdDGBC9mWuknEXM2sB_jVNKk',
    appId: '1:845399101862:ios:a1533a004bc3ebc90fff67',
    messagingSenderId: '845399101862',
    projectId: 'hydrate-349220',
    storageBucket: 'hydrate-349220.appspot.com',
    androidClientId: '845399101862-05j142vf3o72u5pbfod1er178dgcde9e.apps.googleusercontent.com',
    iosClientId: '845399101862-gtpj2n5v61fk3som19hncu2apb98gge5.apps.googleusercontent.com',
    iosBundleId: 'com.example.hydrateApp',
  );
}
